name: Generate 3D Profile

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D contributions
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: reimunyancat
        with:
          USERNAME: reimunyancat
          SETTING_JSON: |
            {
              "type": "normal",
              "backgroundColor": "#0d1117",
              "foregroundColor": "#00b894",
              "strongColor": "#55a3ff",
              "weakColor": "#2f3542",
              "radarColor": "#41d885",
              "growingAnimation": true,
              "contribColors": [
                "#161b22",
                "#00b894",
                "#2ed573",
                "#41d885",
                "#7bed9f"
              ]
            }
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
